### ISSUE TITLE
Constant crashes on 1.12.2: Unexperienced pointed as cause. Forge 2860

### ISSUE THREAD

**Issue by organicmeme** [SmileycorpMC/Unexperienced#2]
Crash report:

https://pastebin.com/x8pw3xjV

**Comment by SmileycorpMC** [comment]
What happened before the crash occured?

**Comment by organicmeme** [comment]
Nothing? It generally happens either at night or during sunrise but it seems to occur randomly during other times as well. Maybe the game doesn't know what to do with the mobs that are killed by the sun or things other than the player?
Sometimes it takes like 30 min of playing to crash, sometimes 5 min and sometimes less than 1.

Worse part is there seems to be absolutely no other mod which disables xp orbs.

**Comment by SmileycorpMC** [comment]
If you go into the config and set B:hideBar to false it should stop the crash, while I work on making a fix for it.

**Comment by organicmeme** [comment]
Thank you!

**Comment by SmileycorpMC** [comment]
Should be fixed as of version 1.12.2-1.2.0a
