### ISSUE TITLE
[1.18/1.19] hideBar config option is ignored when set to false

### ISSUE THREAD

**Issue by MrNovado** [SmileycorpMC/Unexperienced#3]
Great mod!

Though, seems like you forgot to check for `hideBar` when checking on `shouldShowBar` | `renderExperienceBar` .

- Precognition: `hideBar` option is set to `false`.
- Expected: experience bar is always shown as-in vanilla.
- Actual: experience bar is hidden and only shown when holding bottle of enchanting, ie on `showBarItems` | `showBarBlocks`.

**Comment by SmileycorpMC** [comment]
Should be fixed as of version 2.0.0a for 1.18 and 1.19.
