### ISSUE TITLE
1.12.2 crash

### ISSUE THREAD

**Issue by al-wei** [SmileycorpMC/Unexperienced#5]
[crash-2024-02-27_09.53.39-server](https://gist.github.com/al-wei/d5de4062c3794c10d81110a39f9b5d09)

[latest.log](https://gist.github.com/al-wei/a6fe4ea46f7437dd4a4325353c703534)

Unexperienced-1.12.2-1.2.0a
forge-14.23.5.2860

Let my Wolf attack the monster, The game crashed.

**Comment by SmileycorpMC** [comment]
fix as of 1.12.2-1.2.0b
