### ISSUE TITLE
Modrinth?

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [SmileycorpMC/Unexperienced#6]
Hello! Would you mind to upload this to modrinth, or mind me uploading it?

This is one of the few mods still missing for my modpack so I could ditch curseforge :)

**Comment by SmileycorpMC** [comment]
I'll try and get it uploaded tomorrow, I usually forget modrinth exists and forrget to upload there as well, thanks for reminding me.

**Comment by 3x1t-5tyl3** [comment]
> I'll try and get it uploaded tomorrow, I usually forget modrinth exists and forrget to upload there as well, thanks for reminding me.

Thanks. Awesome to hear. :)
